name: RuneMobs
version: 1.0
main: com.darkun7.runemobs.RuneMobs
api-version: 1.13
author: darkun7
description: Adds elite mobs with rarities, custom rune drops, and boss raids

commands:
  runemobs:
    description: Master command for RuneMobs
    usage: |
      /runemobs reload - Reload configuration
      /runemobs give - Give yourself a random rune
      /runemobs summon <mobType> <rarity> - Spawn a mob with rarity
      /runemobs raid <raidName> - Start a raid (OP only)
      /runemobs stopraid - Forcefully stops the currently active boss raid (OP only)
    permission: runemobs.admin

permissions:
  runemobs.admin:
    description: Allows using the /runemobs command
    default: op
